default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5

development:
  <<: *default
  database: deduct_sum_using_join_dev

test:
  <<: *default
  database: deduct_sum_using_join_test

production:
  <<: *default
  database: deduct_sum_using_join_prod
